name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Print GitHub Username
        run: echo "GitHub username is: ${{ secrets.GITHUB_USER_NAME }}"
        
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rahul-Nakka-23
          outputs: dist/snake-${{ github.run_id }}.svg?palette=github-dark # Use dynamic naming to avoid caching

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

